// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkvjefrztgciywvdbbve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrdmplZnJ6dGdjaXl3dmRiYnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NjM1NTYsImV4cCI6MjA1NDIzOTU1Nn0.Wb8rhE4aHczUvd1EmyjYja8zfDAfudtMaWYz8je0c2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);